Acceptance testing
kirster/qna pull request #3
Opened 2018-02-02 15:28 UTC by kirster

2018-02-03 09:31 UTC, vkurennov requested changes

2018-02-03 09:31 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if current_user.author?(@answer)
А если условие не выполнится, что тогда будем рендерить?

2018-02-03 09:31 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if current_user.author?(@question)
Если условие не выполнится, что тогда?

2018-02-03 09:31 UTC, vkurennov commented on app/views/questions/show.html.slim
> +-if @question.answers.any?
Условие тут не нужно, т.к. если ответов нет, то each просто не будет ничего делать. Условие имеет смысл, если ты, например, хочешь вывести строку "ответов нет" или что-то подобное.

2018-02-03 09:31 UTC, vkurennov commented on app/views/questions/show.html.slim
> +        -if user_signed_in? && current_user.author?(answer)
Чтобы не писать двойное условие можно применить оператор safe naviagtion: `if current_user&.author?(answer)`

2018-02-03 09:31 UTC, vkurennov commented on app/views/questions/show.html.slim
> +          = link_to 'Delete answer', answer_path(answer), method: :delete
Можно вторым аргументом передавать просто объект: `link_to 'Delete answer', answer, method: :delete`

2018-02-03 09:31 UTC, vkurennov commented on db/migrate/20180201120118_add_user_id_to_questions_answers.rb
> +    add_column :questions, :user_id, :integer, index: true, null: false
Если использовать add_belongs_to, то не нужно будет писать `index: true`, т.к. он автоматом проставляется. Кроме того, стоит добавитьб опцию foreign_key: true, чтобы включить контроль целостности на уровне БД

2018-02-03 09:31 UTC, vkurennov commented on db/migrate/20180201121709_add_idexes_on_user_in_questions_answers.rb
> +    add_index :questions, :user_id
У тебя же в предыдущей миграции сразу индексы создаются, зачем их еще раз добавлять? И в рамках одной задачи, пока код не слит в мастер, можно просто откатить миграцию и исправить ее. Так лучше, чем плодить множество мелких миграций.

2018-02-03 09:31 UTC, vkurennov commented on spec/acceptance/answers/create_answer_spec.rb
> +    fill_in 'answer[body]', with: 'test answer'
к полям лучше обращаться по меткам, какие видит пользователь.

2018-02-03 09:31 UTC, vkurennov commented on spec/acceptance/answers/create_answer_spec.rb
> +    expect(page).to have_content 'Your answer was successfully created'
Нужно проверить наличие текста ответа на странице

2018-02-03 09:31 UTC, vkurennov commented on spec/acceptance/answers/destroy_answer_spec.rb
> +    answer
Если данные нужн перед тестом, то объявляй их с помощью `given!` (`let!`), в этом случае код из блока будет выполняться перед каждым тестом, а не в момент первого вызова.

2018-02-03 09:31 UTC, vkurennov commented on spec/acceptance/answers/destroy_answer_spec.rb
> +    expect(page).to_not have_content 'Delete answer'
Лучше have_link использовать

2018-02-03 09:31 UTC, vkurennov commented on spec/acceptance/questions/create_question_spec.rb
> +    expect(page).to have_content 'Your question was successfully created'
Надо проверить, что на странице есть заголовок и тело вопроса

2018-02-03 09:31 UTC, vkurennov commented on spec/acceptance/questions/index_question_spec.rb
> +    questions.each { |question| expect(page).to have_content question.title }
Тест верный, но он ложно-положительный, потому что если будет один заголовок выведен, то тест все равно пройдет, ведь все заголовки вопросов одинаковые, он просто несколько раз будет проверен. Чтобы этого избежать, нужно сделать заголовки вопросов уникальными, проще всего через sequence в фабриках.

2018-02-03 09:31 UTC, vkurennov commented on spec/acceptance/questions/show_question_spec.rb
> +    answers.each { |answer| expect(page).to have_content answer.body }
А тут нужны уникальные ответы.

2018-02-03 09:31 UTC, vkurennov commented on spec/models/user_spec.rb
> +describe User do
А где же тесты на метод `author?`? Нужно писать тесты на любой код, который ты пишешь

2018-02-03 09:39 UTC, kirster commented on spec/acceptance/answers/create_answer_spec.rb
> +    fill_in 'answer[body]', with: 'test answer'
Тут паршл, по метке Body не находит

2018-02-04 05:25 UTC, vkurennov approved these changes

2018-02-04 05:25 UTC, vkurennov commented on spec/models/user_spec.rb
> +        expect(user.author?(question)).to eq true
Для методов-предикатов в rspec есть классный синтаксис: `expect(user).to be_author(question)`. Т.е. вызов метода переносим после  to, добавляем be_ и убираем вопр. знак

2018-02-04 06:13 UTC, merged